# Generated by Django 4.1.5 on 2023-01-31 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='amout',
        ),
    ]
