# Generated by Django 4.1.5 on 2023-02-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
        migrations.AddField(
            model_name='donatordonate',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/avatar/'),
        ),
        migrations.AlterField(
            model_name='donatordonate',
            name='birth_certificate_image',
            field=models.ImageField(upload_to='profile/birth_certificate_image/'),
        ),
        migrations.AlterField(
            model_name='donatordonate',
            name='identity_card_image',
            field=models.ImageField(upload_to='profile/identity_card_image/'),
        ),
    ]
