# Generated by Django 4.1.5 on 2023-02-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_profile_identity_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
