# Generated by Django 4.1.5 on 2023-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_donatordonate_donator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatordonate',
            name='birth_certificate_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='donatordonate',
            name='identity_card_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
