# Generated by Django 4.1.5 on 2023-02-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_alter_donatordonate_birth_certificate_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatordonate',
            old_name='donator',
            new_name='user',
        ),
    ]
