# Generated by Django 4.1.5 on 2023-02-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_remove_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
