# Generated by Django 4.1.5 on 2023-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_rename_donator_donatordonate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatordonate',
            name='birth_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
