# Generated by Django 4.1.5 on 2023-02-03 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0005_alter_donatordonate_birth_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatordonate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
